# Generated by Django 3.1.7 on 2021-03-05 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_takeout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='management',
            name='msds',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
